spring.application.name=api_pago

spring.datasource.url=${app_datasource_url}
spring.datasource.username=${app_user}
spring.datasource.password=${app_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Exponer endpoints de Actuator
management.endpoints.web.exposure.include=health,info,prometheus

# Info endpoint
management.info.env.enabled=true

# Prometheus
management.endpoint.prometheus.access=READ_ONLY
management.prometheus.metrics.export.enabled=true

info.app.name=API Pagos
info.app.version=1.0.0
info.app.description=Payments API built with Spring Boot

# Nivel global
logging.level.root=INFO

# Tu app
logging.level.com.tomas.payments=DEBUG

# SQL (opcional)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n